[package]
name = "vex-prover"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[dependencies]
stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "754088c", features = ["parallel"] }
stwo-air-utils = { git = "https://github.com/starkware-libs/stwo", rev = "754088c" }
tracing = "0.1"
itertools = "0.12.0"
num-traits = "0.2.19"
rayon = { version = "1.10.0" }

[dev-dependencies]
tracing-subscriber = "0.3"
rand = "0.8.5"
criterion = { version = "0.5", features = ["html_reports"] }
vex-matching-engine = { git = "https://github.com/aerius-labs/VEX-matching-engine.git" }
test-log = { version = "0.2.15", features = ["trace"] }

[[bench]]
name = "raw_insertions"
harness = false