use std::array;

use super::instruction::{Opcode, N_INSTRUCTION_FELTS};
use crate::{
    components::{
        bytes::ByteOperations,
        less_than::{LessThanColumn, LessThanOperations},
        poseidon::PoseidonOperations,
    },
    imt::{error::IMTError, LeafFelts},
    types::N_U64_LIMBS,
};
use itertools::{chain, izip, Itertools};
use num_traits::{One, Zero};
use stwo_prover::core::{
    backend::{simd::column::BaseColumn, Column},
    fields::m31::BaseField,
};

pub type Instructions<F> = Vec<[F; N_INSTRUCTION_FELTS]>;
pub type InstructionFelts<F> = [F; N_INSTRUCTION_FELTS];

/// ExecutionTrace contains Instructions executed by matching engine during the execution
/// There are two types of events:
/// 1. User Events: Events that are generated by the user
///     - Place Order: User places an order
///     - Cancel Order: User cancels an order
///     - Modify Order: User modifies an order
/// 2. System Events: Events that are generated by the system
///     - Order Matched: Two orders are matched
///     - Order Partial Matched: An order is cancelled
///
/// Each Event corresponds to a Tree Instruction in IndexedMerkleTree
/// These events occur in Buy as well as Sell side, so there are total of 10 Instruction Types
///
/// These Instructions require additional Auxillary Operations to be computed for Constraint Evaluation
/// 1. Add Operations: Add two Field Elements
/// 2. Less Than Operations: Compare two Price pairs, comprising 8 Field Elements each
/// 3. Comparison Operations: Compare two Price, Time pairs
/// 4. Hash Operations: Poseidon Hash Operations
/// 5. Byte Operations: U8 Operations such as and, less than, range check
pub struct ExecutionTrace<F> {
    /// Buy Side Instructions
    /// 1. Place Buy Order
    pub buy_insert_order: Instructions<F>,
    /// 2. Cancel Buy Order
    pub buy_delete_order: Instructions<F>,
    /// 3. Modify Buy Order
    pub buy_modify_order: Instructions<F>,
    /// 4. Buy Order Matched
    pub buy_order_match: Instructions<F>,
    /// 5. Buy Order Cancelled
    pub buy_order_partially_match: Instructions<F>,
    /// Sell Side Instructions
    /// 6. Place Sell Order
    pub sell_insert_order: Instructions<F>,
    /// 7. Cancel Sell Order
    pub sell_delete_order: Instructions<F>,
    /// 8. Modify Sell Order
    pub sell_modify_order: Instructions<F>,
    /// 9. Sell Order Matched
    pub sell_order_match: Instructions<F>,
    /// 10. Sell Order Cancelled
    pub sell_order_partially_match: Instructions<F>,
    /// All The Instructions sequentially ordered for the Main Trace
    pub instructions: Instructions<F>,
    /// Auxillary Operations that are Looked up by the above instructions
    /// Add Operation for Field Representations of Price, Time
    pub add_operations: Vec<[F; 31]>,
    /// Less Than Operation. Compares Price pairs, comprising 8 Field Elements each
    pub less_than_operations: LessThanOperations,
    /// strict less than operations
    pub strict_less_than_operations: LessThanOperations,
    /// Comparison Operations. Compares two Price, Time pairs
    pub comparision_operations: Vec<[F; 53]>,
    /// Hash Operations For Merklelization.
    pub poseidon_operations: PoseidonOperations,
    /// Uint8 Operations
    pub byte_operations: ByteOperations,
}

impl Default for ExecutionTrace<BaseField> {
    fn default() -> Self {
        Self::new()
    }
}

impl ExecutionTrace<BaseField> {
    /// Creates a new Execution Trace
    pub fn new() -> Self {
        Self {
            buy_insert_order: Vec::new(),
            buy_delete_order: Vec::new(),
            buy_modify_order: Vec::new(),
            buy_order_match: Vec::new(),
            buy_order_partially_match: Vec::new(),
            sell_insert_order: Vec::new(),
            sell_delete_order: Vec::new(),
            sell_modify_order: Vec::new(),
            sell_order_match: Vec::new(),
            sell_order_partially_match: Vec::new(),
            instructions: Vec::new(),
            add_operations: Vec::new(),
            less_than_operations: Vec::new(),
            strict_less_than_operations: Vec::new(),
            comparision_operations: Vec::new(),
            poseidon_operations: Vec::new(),
            byte_operations: array::from_fn(|_| unsafe { BaseColumn::uninitialized(1 << 16) }),
        }
    }

    /// Adds an instruction to the Execution Trace
    pub fn add_instruction(&mut self, instruction: InstructionFelts<BaseField>) {
        match Opcode::from_field(instruction[0]) {
            Opcode::InsertBuyOrder => self.buy_insert_order.push(instruction),
            Opcode::CancelBuyOrder => self.buy_delete_order.push(instruction),
            Opcode::UpdateBuyOrder => self.buy_modify_order.push(instruction),
            Opcode::MatchBuyOrder => self.buy_order_match.push(instruction),
            Opcode::PartialMatchBuyOrder => self.buy_order_partially_match.push(instruction),
            Opcode::InsertSellOrder => self.sell_insert_order.push(instruction),
            Opcode::CancelSellOrder => self.sell_insert_order.push(instruction),
            Opcode::UpdateSellOrder => self.sell_modify_order.push(instruction),
            Opcode::MatchSellOrder => self.sell_order_match.push(instruction),
            Opcode::PartialMatchSellOrder => self.sell_order_partially_match.push(instruction),
        }
        self.instructions.push(instruction);
    }

    //@todo: the following methods will take input as an event
    // and compute the corresponding Trace Row For constraint evaluations
    /// Adds an Add Event to the Execution Trace
    pub fn add_add_event(&mut self, event: [BaseField; 31]) {
        self.add_operations.push(event);
    }

    /// Adds a Less Than Event by recording the corresponding Trace Row
    /// Returns an error if any limb in a or b is greater than 255
    pub fn add_strictly_less_than_event(
        &mut self,
        a: [BaseField; N_U64_LIMBS],
        b: [BaseField; N_U64_LIMBS],
    ) -> Result<(), IMTError> {
        self.add_less_than_event_internal(a, b, true)
    }

    /// Adds a Less Than Event by recording the corresponding Trace Row
    /// Returns an error if any limb in a or b is greater than 255
    pub fn add_less_than_event(
        &mut self,
        a: [BaseField; N_U64_LIMBS],
        b: [BaseField; N_U64_LIMBS],
    ) -> Result<(), IMTError> {
        self.add_less_than_event_internal(a, b, false)
    }

    /// Adds a Comparison Event by recording the corresponding Trace Row
    pub fn add_comparison_event(&mut self, event: [BaseField; 53]) {
        self.comparision_operations.push(event);
    }

    /// Adds a Poseidon Event by recording the corresponding Trace Row
    pub fn add_merkle_hash_event(&mut self, a: [BaseField; 8], b: [BaseField; 8]) {
        self.poseidon_operations
            .push(chain!(a, b).collect_vec().try_into().unwrap());
    }

    /// Add a Leaf Hash Event
    pub fn add_leaf_hash_event(&mut self, leaf_felts: &LeafFelts<BaseField>) {
        // @todo: The Hash Function is not implemented.
        // Only the first 16 elements are taken into account
        self.poseidon_operations
            .push(leaf_felts[0..16].try_into().unwrap());
    }

    /// Adds an And U8 Event by recording the corresponding Trace Row
    /// Returns an error if a or b is greater than 255
    pub fn add_and_u8_event(&mut self, a: u32, b: u32) -> Result<(), IMTError> {
        assert!(a < 256 && b < 256, "Invalid U8 Pair");
        let offset = (a << 8) + b;
        self.byte_operations[0].as_mut_slice()[offset as usize].0 += 1;
        Ok(())
    }

    /// Adds a Less Than U8 Event by recording the corresponding Trace Row
    /// Returns an error if a or b is greater than 255
    pub fn add_less_than_u8_event(&mut self, a: u32, b: u32) -> Result<(), IMTError> {
        assert!(a < 256 && b < 256, "Invalid U8 Pair");
        let offset = (a << 8) + b;
        self.byte_operations[1].as_mut_slice()[offset as usize].0 += 1;
        Ok(())
    }

    /// Adds a Range Check U8 Event by recording the corresponding Trace Row
    /// Returns an error if a or b is greater than 255
    pub fn add_range_check_u8_event(&mut self, a: u32, b: u32) -> Result<(), IMTError> {
        assert!(a < 256 && b < 256, "Invalid U8 Pair");
        let offset = (a << 8) + b;
        self.byte_operations[2].as_mut_slice()[offset as usize].0 += 1;
        Ok(())
    }

    /// Adds a Less Than Event by recording the corresponding Trace Row
    /// the strict flag is used to determine if the comparison is strict
    /// # Returns
    ///  - Ok(()) if the operation is successful
    ///  - InvalidU8Pair(a, b) if a or b is greater than 255
    fn add_less_than_event_internal(
        &mut self,
        a: [BaseField; N_U64_LIMBS],
        b: [BaseField; N_U64_LIMBS],
        is_strict: bool,
    ) -> Result<(), IMTError> {
        let mut row = [BaseField::zero(); LessThanColumn::IS_REAL + 1];
        row[LessThanColumn::A..LessThanColumn::B].copy_from_slice(&a);
        row[LessThanColumn::B..LessThanColumn::C].copy_from_slice(&b);

        let flags = &mut row[LessThanColumn::FLAGS..LessThanColumn::A_COMPARISON_BYTE];
        let mut c = BaseField::zero();
        let mut a_cmp = BaseField::zero();
        let mut b_cmp = BaseField::zero();

        for (a_byte, b_byte, flag) in izip!(a.iter().rev(), b.iter().rev(), flags.iter_mut().rev())
        {
            if a_byte.0 > 255 || b_byte.0 > 255 {
                return Err(IMTError::InvalidU8Pair(a_byte.0, b_byte.0));
            }
            match a_byte.cmp(b_byte) {
                std::cmp::Ordering::Less => {
                    *flag = BaseField::one();
                    a_cmp = *a_byte;
                    b_cmp = *b_byte;
                    c = BaseField::one();
                    break;
                }
                std::cmp::Ordering::Greater => {
                    *flag = BaseField::one();
                    a_cmp = *a_byte;
                    b_cmp = *b_byte;
                    break;
                }
                _ => {}
            }
        }

        // less_than_u8 events for a_cmp and b_cmp bytes
        self.add_less_than_u8_event(a_cmp.0, b_cmp.0)?;
        row[LessThanColumn::A_COMPARISON_BYTE] = a_cmp;
        row[LessThanColumn::B_COMPARISON_BYTE] = b_cmp;
        row[LessThanColumn::IS_REAL] = BaseField::one();

        if is_strict {
            row[LessThanColumn::C] = c;
            self.strict_less_than_operations.push(row);
        } else {
            // returns 1 as result if a = b, else returns c
            row[LessThanColumn::C] = if a == b { BaseField::one() } else { c };
            self.less_than_operations.push(row);
        }

        Ok(())
    }
}
