use crate::components::TraceSize;
use itertools::izip;
use num_traits::{One, Zero};
use std::array;
use stwo_prover::core::{
    backend::{simd::column::BaseColumn, Column},
    fields::m31::BaseField,
};

use super::instruction::{Instruction, Opcode};
use crate::{
    components::{
        addition::AddColumn,
        bytes::ByteOperations,
        less_than::{LessThanColumn, LessThanOperations},
    },
    types::N_U64_LIMBS,
};

/// Poseidon Operations
/// Containts State of the Poseidon Hash Function during Permutation
/// Index: 0-16: Initial State
/// Index: 16-80: First 4 Full Rounds End: 16 + 4 * 16 = 80
/// Index: 80-94: 14 Partial Rounds End Applied to state[0]: 80 + 14 = 94
/// Index: 94-158: Last 4 Full Rounds End: 94 + 4 * 16 = 158
pub type PoseidonOperations = Vec<[BaseField; 158]>;

pub enum AddOperationError {
    InputLimbExceedsRange,
    FinalLimbOverflow,
}
#[derive(Debug)]
pub enum RangeCheckError {
    InputLimbExceedsRange,
}
/// ExecutionTrace contains Instructions executed by matching engine during the execution
/// There are two types of events:
/// 1. User Events: Events that are generated by the user
///     - Place Order: User places an order
///     - Cancel Order: User cancels an order
///     - Modify Order: User modifies an order
/// 2. System Events: Events that are generated by the system
///     - Order Matched: Two orders are matched
///     - Order Partial Matched: An order is cancelled
///
/// Each Event corresponds to a Tree Instruction in IndexedMerkleTree
/// These events occur in Buy as well as Sell side, so there are total of 10 Instruction Types
///
/// These Instructions require additional Auxillary Operations to be computed for Constraint Evaluation
/// 1. Add Operations: Add two Field Elements
/// 2. Less Than Operations: Compare two Price pairs, comprising 8 Field Elements each
/// 3. Comparison Operations: Compare two Price, Time pairs
/// 4. Hash Operations: Poseidon Hash Operations
/// 5. Byte Operations: U8 Operations such as and, less than, range check
pub struct ExecutionTrace<F> {
    /// Buy Side Instructions
    /// 1. Place Buy Order
    pub buy_place_order: Vec<Instruction<F>>,
    /// 2. Cancel Buy Order
    pub buy_cancel_order: Vec<Instruction<F>>,
    /// 3. Modify Buy Order
    pub buy_modify_order: Vec<Instruction<F>>,
    /// 4. Buy Order Matched
    pub buy_order_match: Vec<Instruction<F>>,
    /// 5. Buy Order Cancelled
    pub buy_order_partially_match: Vec<Instruction<F>>,
    /// Sell Side Instructions
    /// 6. Place Sell Order
    pub sell_place_order: Vec<Instruction<F>>,
    /// 7. Cancel Sell Order
    pub sell_cancel_order: Vec<Instruction<F>>,
    /// 8. Modify Sell Order
    pub sell_modify_order: Vec<Instruction<F>>,
    /// 9. Sell Order Matched
    pub sell_order_match: Vec<Instruction<F>>,
    /// 10. Sell Order Cancelled
    pub sell_order_partially_match: Vec<Instruction<F>>,
    /// All The Instructions sequentially ordered for the Main Trace
    pub instructions: Vec<Instruction<F>>,
    /// Auxillary Operations that are Looked up by the above instructions
    /// Add Operation for Field Representations of Price, Time
    pub add_operations: Vec<[F; 32]>,
    /// Less Than Operation. Compares Price pairs, comprising 8 Field Elements each
    pub less_than_operations: LessThanOperations,
    /// Comparison Operations. Compares two Price, Time pairs
    pub comparision_operations: Vec<[F; 53]>,
    /// Hash Operations For Merklelization.
    pub poseidon_operations: PoseidonOperations,
    /// Uint8 Operations
    pub byte_operations: ByteOperations,
}

impl Default for ExecutionTrace<BaseField> {
    fn default() -> Self {
        Self::new()
    }
}

impl ExecutionTrace<BaseField> {
    /// Creates a new Execution Trace
    pub fn new() -> Self {
        Self {
            buy_place_order: Vec::new(),
            buy_cancel_order: Vec::new(),
            buy_modify_order: Vec::new(),
            buy_order_match: Vec::new(),
            buy_order_partially_match: Vec::new(),
            sell_place_order: Vec::new(),
            sell_cancel_order: Vec::new(),
            sell_modify_order: Vec::new(),
            sell_order_match: Vec::new(),
            sell_order_partially_match: Vec::new(),
            instructions: Vec::new(),
            add_operations: Vec::new(),
            less_than_operations: Vec::new(),
            comparision_operations: Vec::new(),
            poseidon_operations: Vec::new(),
            byte_operations: array::from_fn(|_| unsafe { BaseColumn::uninitialized(1 << 16) }),
        }
    }

    /// Adds an instruction to the Execution Trace
    pub fn add_instruction(&mut self, instruction: Instruction<BaseField>) {
        match instruction.opcode {
            Opcode::PlaceBuyOrder => self.buy_place_order.push(instruction),
            Opcode::CancelBuyOrder => self.buy_cancel_order.push(instruction),
            Opcode::UpdateBuyOrder => self.buy_modify_order.push(instruction),
            Opcode::ExecuteBuyOrder => self.buy_order_match.push(instruction),
            Opcode::PartialExecuteBuyOrder => self.buy_order_partially_match.push(instruction),
            Opcode::PlaceSellOrder => self.sell_place_order.push(instruction),
            Opcode::CancelSellOrder => self.sell_cancel_order.push(instruction),
            Opcode::UpdateSellOrder => self.sell_modify_order.push(instruction),
            Opcode::ExecuteSellOrder => self.sell_order_match.push(instruction),
            Opcode::PartialExecuteSellOrder => self.sell_order_partially_match.push(instruction),
        }
        self.instructions.push(instruction);
    }

    //@todo: the following methods will take input as an event
    // and compute the corresponding Trace Row For constraint evaluations
    /// Adds an Add Event to the Execution Trace
    // pub fn add_add_event(&mut self, event: [BaseField; 31]) {
    //     self.add_operations.push(event);
    // }
    /// Adds an Add Event to the Execution Trace
    pub fn add_add_event(&mut self, a: [BaseField; N_U64_LIMBS], b: [BaseField; N_U64_LIMBS]) -> Result<(), AddOperationError> {
        let mut row = [BaseField::zero(); AddColumn::MAIN_COLS];

        // Perform range checks for input limbs
        for &limb_a in a.iter() {
            let limb_value = limb_a.0;
            if limb_value > 255 {
                return Err(AddOperationError::InputLimbExceedsRange);
            }
            // Add range check for each limb of a
            self.add_range_check_u8_event(limb_value, 0); // Using 0 as a dummy second parameter
        }

        for &limb_b in b.iter() {
            let limb_value = limb_b.0;
            if limb_value > 255 {
                return Err(AddOperationError::InputLimbExceedsRange);
            }
            // Add range check for each limb of b
            self.add_range_check_u8_event(limb_value, 0); // Using 0 as a dummy second parameter
        }

        // Copy input operands a and b into the trace row
        row[AddColumn::A..AddColumn::B].copy_from_slice(&a);
        row[AddColumn::B..AddColumn::C].copy_from_slice(&b);

        let mut carry = [BaseField::zero(); N_U64_LIMBS - 1];
        let mut c = [BaseField::zero(); N_U64_LIMBS];

        for i in 0..7 {
            let sum = a[i]
                + b[i]
                + (if i > 0 {
                    carry[i - 1]
                } else {
                    BaseField::zero()
                });

            if sum > BaseField::from(255) {
                c[i] = sum - BaseField::from(256);
                carry[i] = BaseField::one();
            } else {
                c[i] = sum;
                carry[i] = BaseField::zero();
            }

            // Add range check for each output limb
            self.add_range_check_u8_event(c[i].0, 0);
        }

        let last_sum = a[7] + b[7] + carry[6];
        if last_sum > BaseField::from(255) {
            return Err(AddOperationError::FinalLimbOverflow);
        }
        c[7] = last_sum;

        // Add range check for the final output limb
        self.add_range_check_u8_event(c[7].0, 0);

        // Copy computed c and carry values into the row
        row[AddColumn::C..AddColumn::CARRY].copy_from_slice(&c);
        row[AddColumn::CARRY..AddColumn::IS_REAL].copy_from_slice(&carry);

        // Mark this as a real operation
        row[AddColumn::IS_REAL] = BaseField::one();

        self.add_operations.push(row);
        Ok(())
    }

    /// Adds a Less Than Event by recording the corresponding Trace Row
    pub fn add_less_than_event(
        &mut self,
        a: [BaseField; N_U64_LIMBS],
        b: [BaseField; N_U64_LIMBS],
    ) {
        let mut row = [BaseField::zero(); LessThanColumn::IS_REAL + 1];
        row[LessThanColumn::A..LessThanColumn::B].copy_from_slice(&a);
        row[LessThanColumn::B..LessThanColumn::C].copy_from_slice(&b);

        let flags = &mut row[LessThanColumn::FLAGS..LessThanColumn::A_COMPARISON_BYTE];
        let mut c = BaseField::zero();
        let mut a_cmp = BaseField::zero();
        let mut b_cmp = BaseField::zero();

        for (a_byte, b_byte, flag) in izip!(a.iter().rev(), b.iter().rev(), flags.iter_mut().rev())
        {
            match a_byte.cmp(b_byte) {
                std::cmp::Ordering::Less => {
                    *flag = BaseField::one();
                    a_cmp = *a_byte;
                    b_cmp = *b_byte;
                    c = BaseField::one();
                    break;
                }
                std::cmp::Ordering::Greater => {
                    *flag = BaseField::one();
                    a_cmp = *a_byte;
                    b_cmp = *b_byte;
                    break;
                }
                _ => {}
            }
        }

        row[LessThanColumn::C] = c;
        row[LessThanColumn::A_COMPARISON_BYTE] = a_cmp;
        row[LessThanColumn::B_COMPARISON_BYTE] = b_cmp;
        row[LessThanColumn::IS_REAL] = BaseField::one();

        self.less_than_operations.push(row);
    }

    /// Adds a Comparison Event by recording the corresponding Trace Row
    pub fn add_comparison_event(&mut self, event: [BaseField; 53]) {
        self.comparision_operations.push(event);
    }

    /// Adds a Poseidon Event by recording the corresponding Trace Row
    pub fn add_poseidon_event(&mut self, event: [BaseField; 158]) {
        self.poseidon_operations.push(event);
    }

    /// Adds an And U8 Event by recording the corresponding Trace Row
    /// # Panics
    /// Panics if a or b is greater than 255
    pub fn add_and_u8_event(&mut self, a: u32, b: u32) {
        assert!(a < 256 && b < 256, "Invalid U8 Pair");
        let offset = (a << 8) + b;
        self.byte_operations[0].as_mut_slice()[offset as usize].0 += 1;
    }

    /// Adds a Less Than U8 Event by recording the corresponding Trace Row
    /// # Panics
    /// Panics if a or b is greater than 255
    pub fn add_less_than_u8_event(&mut self, a: u32, b: u32) {
        assert!(a < 256 && b < 256, "Invalid U8 Pair");
        let offset = (a << 8) + b;
        self.byte_operations[1].as_mut_slice()[offset as usize].0 += 1;
    }

    /// Adds a Range Check U8 Event by recording the corresponding Trace Row.
    /// 
    /// # Errors
    /// Returns a `RangeCheckError::InputLimbExceedsRange` if `a` or `b` is greater than 255.
    pub fn add_range_check_u8_event(&mut self, a: u32, b: u32) {
        if a >= 256 || b >= 256 {
            eprintln!("Error: {:?}", RangeCheckError::InputLimbExceedsRange);
            return; // Simply exit without modifying data
        }
    
        let offset = (a << 8) + b;
        self.byte_operations[2].as_mut_slice()[offset as usize].0 += 1;
    }
    
    

    
}
