use std::array;

use stwo_prover::core::{
    backend::{simd::column::BaseColumn, Column},
    fields::m31::BaseField,
};

use super::instruction::{Instruction, Opcode};

//@todo: Move Event Types to specific components
/// Byte Events for U8 Operations
/// Index- 0: multiplicities of and operation for a u8 pair
/// Index- 1: multiplicities of less than range checks for u8 pairs. checks a < b < 256
/// Index- 2: multiplicities of range check for a pair of u8. checks if a < 256 && b < 256
pub type ByteEvents = [BaseColumn; 3];

/// Poseidon Events
/// Containts State of the Poseidon Hash Function during Permutation
/// Index: 0-16: Initial State
/// Index: 16-80: First 4 Full Rounds End: 16 + 4 * 16 = 80
/// Index: 80-94: 14 Partial Rounds End Applied to state[0]: 80 + 14 = 94
/// Index: 94-158: Last 4 Full Rounds End: 94 + 4 * 16 = 158
pub type PoseidonEvents = Vec<[BaseField; 158]>;

/// ExecutionTrace contains Instructions executed by matching engine during the execution
/// There are two types of events:
/// 1. User Events: Events that are generated by the user
///     - Place Order: User places an order
///     - Cancel Order: User cancels an order
///     - Modify Order: User modifies an order
/// 2. System Events: Events that are generated by the system
///     - Order Matched: Two orders are matched
///     - Order Partial Matched: An order is cancelled
/// Each Event corresponds to a Tree Instruction in IndexedMerkleTree
/// These events occur in Buy as well as Sell side, so there are total of 10 Instruction Types
/// These Instructions require additional Auxillary Operations to be computed for Constraint Evaluation
/// 1. Add Operations: Add two Field Elements
/// 2. Less Than Operations: Compare two Price pairs, comprising 8 Field Elements each
/// 3. Comparision Operations: Compare two Price, Time pairs
/// 4. Hash Operations: Poseidon Hash Operations
/// 5. Byte Operations: U8 Operations such as and, less than, range check
pub struct ExecutionTrace<F> {
    /// Buy Side Events
    /// 1. Place Buy Order
    buy_place_order: Vec<Instruction<F>>,
    /// 2. Cancel Buy Order
    buy_cancel_order: Vec<Instruction<F>>,
    /// 3. Modify Buy Order
    buy_modify_order: Vec<Instruction<F>>,
    /// 4. Buy Order Matched
    buy_order_match: Vec<Instruction<F>>,
    /// 5. Buy Order Cancelled
    buy_order_partially_match: Vec<Instruction<F>>,
    /// Sell Side Events
    /// 6. Place Sell Order
    sell_place_order: Vec<Instruction<F>>,
    /// 7. Cancel Sell Order
    sell_cancel_order: Vec<Instruction<F>>,
    /// 8. Modify Sell Order
    sell_modify_order: Vec<Instruction<F>>,
    /// 9. Sell Order Matched
    sell_order_match: Vec<Instruction<F>>,
    /// 10. Sell Order Cancelled
    sell_order_partially_match: Vec<Instruction<F>>,
    /// All The Instructions sequentially ordered for the Main Trace
    instructions: Vec<Instruction<F>>,
    /// Auxillary Events that are Looked up by the above events
    /// Add Events
    add_operations: Vec<[F; 31]>,
    /// Less Than Events. Compares Price pairs, comprising 8 Field Elements each
    less_than_operations: Vec<[F; 26]>,
    /// Comparision Events. Compares two Price, Time pairs
    comparision_operations: Vec<[F; 53]>,
    /// Hash Events.
    posiedon_operations: PoseidonEvents,
    /// Byte Events for U8 Operations
    pub byte_operations: ByteEvents,
}

impl ExecutionTrace<BaseField> {
    /// Creates a new Execution Trace
    pub fn new() -> Self {
        Self {
            buy_place_order: Vec::new(),
            buy_cancel_order: Vec::new(),
            buy_modify_order: Vec::new(),
            buy_order_match: Vec::new(),
            buy_order_partially_match: Vec::new(),
            sell_place_order: Vec::new(),
            sell_cancel_order: Vec::new(),
            sell_modify_order: Vec::new(),
            sell_order_match: Vec::new(),
            sell_order_partially_match: Vec::new(),
            instructions: Vec::new(),
            add_operations: Vec::new(),
            less_than_operations: Vec::new(),
            comparision_operations: Vec::new(),
            posiedon_operations: Vec::new(),
            byte_operations: array::from_fn(|_| unsafe { BaseColumn::uninitialized(1 << 16) }),
        }
    }

    /// Adds an instruction to the Execution Trace
    pub fn add_instruction(&mut self, instruction: Instruction<BaseField>) {
        match instruction.opcode {
            Opcode::PlaceBuyOrder => self.buy_place_order.push(instruction),
            Opcode::CancelBuyOrder => self.buy_cancel_order.push(instruction),
            Opcode::UpdateBuyOrder => self.buy_modify_order.push(instruction),
            Opcode::ExecuteBuyOrder => self.buy_order_match.push(instruction),
            Opcode::PartialExecuteBuyOrder => self.buy_order_partially_match.push(instruction),
            Opcode::PlaceSellOrder => self.sell_place_order.push(instruction),
            Opcode::CancelSellOrder => self.sell_cancel_order.push(instruction),
            Opcode::UpdateSellOrder => self.sell_modify_order.push(instruction),
            Opcode::ExecuteSellOrder => self.sell_order_match.push(instruction),
            Opcode::PartialExecuteSellOrder => self.sell_order_partially_match.push(instruction),
        }
        self.instructions.push(instruction);
    }

    //@todo: the following methods will take input as an event
    // and compute the corresponding Trace Row For constraint evaluations
    /// Adds an Add Event to the Execution Trace
    pub fn add_add_event(&mut self, event: [BaseField; 31]) {
        self.add_operations.push(event);
    }

    /// Adds a Less Than Event by recording the corresponding Trace Row
    pub fn add_less_than_event(&mut self, event: [BaseField; 26]) {
        self.less_than_operations.push(event);
    }

    /// Adds a Comparison Event by recording the corresponding Trace Row
    pub fn add_comparison_event(&mut self, event: [BaseField; 53]) {
        self.comparision_operations.push(event);
    }

    /// Adds a Poseidon Event by recording the corresponding Trace Row
    pub fn add_poseidon_event(&mut self, event: [BaseField; 158]) {
        self.posiedon_operations.push(event);
    }

    /// Adds an And U8 Event by recording the corresponding Trace Row
    pub fn add_and_u8_event(&mut self, a: u32, b: u32) {
        let offset = (a << 8) + b;
        self.byte_operations[0].as_mut_slice()[offset as usize].0 += 1;
    }

    /// Adds a Less Than U8 Event by recording the corresponding Trace Row
    pub fn add_less_than_u8_event(&mut self, a: u32, b: u32) {
        let offset = (a << 8) + b;
        self.byte_operations[1].as_mut_slice()[offset as usize].0 += 1;
    }

    /// Adds a Range Check U8 Event by recording the corresponding Trace Row
    pub fn add_range_check_u8_event(&mut self, a: u32, b: u32) {
        let offset = (a << 8) + b;
        self.byte_operations[2].as_mut_slice()[offset as usize].0 += 1;
    }
}
